# Site settings
title: IsMoreiraKt
description: "A blog about programming and technology."
baseurl: "/"
url: "https://ismoreiraktblog.vercel.app/"

# Author
author:
  name: Ismael Moreira
  url: https://github.com/IsMoreiraKt
  email: ismoreirakt@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
